### ISSUE TITLE
When you click on the badge...

### ISSUE THREAD

**Issue by cmcavoy** [davelester/WPBadgeDisplay#12]
Can it go to the backpack display page instead of the criteria page?

**Comment by davelester** [comment]
Good idea -- the criteria pages are going to be pretty inconsistent since each issuer controls them.

Since right now badges are made public at a group level (I know that's going to change to being done at a badge-level), the only link to the backpack server that's available is for the entire public group. In the meantime, I could scrap the links to individual badge criteria and make the group name in the widget a link to the backpack display page.
