### ISSUE TITLE
Last badge uploaded is always the image of the for the award

### ISSUE THREAD

**Issue by Michaelboll** [davelester/WPBadgeDisplay#16]
Hi Dave,

Love this widget. 

I have a problem though.   When I upload more than one badge to the repository on our server, the artwork for the badge is always the last badge uploaded.

For example, I have uploaded artwork for the following badges:
1. Camera Angles
2. Your first badge!

When I go to give the badge for "your f
![Uploading Screen Shot 2013-01-14 at 2.13.05 PM.png . . .]()
irst badge" it sends the "Camera Angles" badge instead.

This problem happens no matter which artwork I use or how many badges I have in my repository.

Any suggestions?

 Thanks,

Mike

![Screen Shot 2013-01-14 at 2 13 05 PM](https://f.cloud.github.com/assets/3025201/63853/835a67bc-5e11-11e2-8466-fe2a3f8e50be.png)
![Screen Shot 2013-01-14 at 2 13 05 PM](https://f.cloud.github.com/assets/3025201/63855/89f524e0-5e11-11e2-96bb-0e6ffb4a31fe.png)

**Comment by davelester** [comment]
What's strange about the two screencaptures you took is that they both specify the same badge criteria, in addition to the image being the same. I'd like to confirm that there isn't a problem with the form saving.

When you award a badge, can you confirm that you're selecting the "your first badge" badge, and that it instead saves as the camera angles badge?

**Comment by Michaelboll** [comment]
Hi Dave,

I put up the two pictures to illustrate that regardless of what badge I select, it always picks the most recent upload. 

Goofy.  ;-)

I did for sure select the "First Badge"   badge, but it pulled up the most recent badge instead.

Thank you so much for your attention to this issue!

**Comment by davelester** [comment]
Michael: I just realized that this issue was posted here for the WPBadgeDisplay plugin, when it should really be posted for WPBadger https://github.com/davelester/WPBadger/issues?state=open. No worries.

If you haven't begun issuing badges yet and are willing to experiment, could you try downloading the latest plugin code that's on github? https://github.com/davelester/WPBadger If you're a git user, you can clone the repository. If not, there's a button to download it as a zip file. You should uninstall the existing plugin and remove the files before trying to install the new one.

I believe the error will go away with the latest code, but want to confirm.

Thanks!

**Comment by Michaelboll** [comment]
I just tried it, and it looks better.  But.. when I get the email for the award, there is no longer a link to accept the award.
